### PR TITLE
Add support for W3C tracing headers

### PR DESCRIPTION
**Pull request by tlwr**
### A short explanation of the proposed change:

Add support for [W3C tracing headers](https://www.w3.org/TR/trace-context/) as requested in https://github.com/cloudfoundry/gorouter/issues/260

I have chosen to follow Go convention and use canonicalised headers `Traceparent` and `Tracestate` instead of rigorously following the spec (which supports `Traceparent` and `traceparent` but prefers the latter).

I have implemented this such that there are no interactions with the existing Zipkin headers, in order to reduce complexity.

I have added new configuration parameters, under the tracing section:

- `enable_w3c` - which controls whether W3C headers are added
- `w3c_tenant_id` - which is an optional parameter which species the tenant ID
  - if not specified the gorouter's tracestate is `gorouter`
  - if it is specified then it is prepended: e.g. `my-tenant-id@gorouter`

I have slightly refactored how headers get logged, because before it was kind of Zipkin specific.

### Instructions to functionally test the behavior change using operator interfaces (BOSH manifest, logs, curl, and metrics)

Run the tests

Deploy gorouter and observe the new headers using `curl`, any requests to Gorouter should set the `Traceparent` and `Tracestate` headers, similar to `X-Vcap-Request-Id`

### Expected result after the change

When making requests to Gorouter, there should be the `Traceparent` and `Tracestate` headers set, in accordance with the W3C spec.

### Current result before the change

There are no interactions with the `Traceparent` and `Tracestate` headers

### Checklist

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `master` branch

* [x] I have run all the unit tests using `bin/test`

* [ ] I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by ameowlia** [comment]
Hi @tlwr, 

Thank you for the pull request including tests! Your work is very much appreciated. 

Before I merge this, do you mind making the a PR with the required changes to routing-release to make these config properties actually configurable? 

Here is the property `enable_zipkin` to use as a guide: 
- [spec change](https://github.com/cloudfoundry/routing-release/blob/4d19a6136ead5e3f441803faf4c6d485919171e4/jobs/gorouter/spec#L218-L220)
- [template change](https://github.com/cloudfoundry/routing-release/blob/4d19a6136ead5e3f441803faf4c6d485919171e4/jobs/gorouter/templates/gorouter.yml.erb#L52-L53)
- [test change](https://github.com/cloudfoundry/routing-release/blob/de344eee9fa178248d9b3dcb9d0ec8f42da51f01/spec/gorouter_templates_spec.rb#L45-L47)


Thanks, 
Amelia, CF Networking Team Member

**Comment by tlwr** [comment]
Thanks! Yup I'll do that later tonight

**Comment by tlwr** [comment]
:+1: I have raised https://github.com/cloudfoundry/routing-release/pull/160

**Comment by adobley** [comment]
I've run CATs and RATs with all the different combos with cloudfoundry/routing-release#160 as well. Everything looks good. Going to merge this and cloudfoundry/routing-release#160.

Thank you @tlwr! ✨

**Pull request merged**
