### PR TITLE
Update dropsonde

### PR DESCRIPTION
**Pull request by fraenkel**
- Dropsonde emits one event HttpStartStop for each request.
- A request metric will always be emitted rather than potentially dropped if
  it exceeded 1 minute.

- Move flag parsing into main to allow current Go versions to work

### CODE REVIEW

**Comment by fraenkel** [comment]
Go 1.3 should be removed from Travis.
Go 1.5 and higher fails because of the race as mentioned #103

**Comment by shalako** [comment]
Could you please provide acceptance criteria for these changes?

- Dropsonde emits one event HttpStartStop for each request.
If this is a change, what is the current behavior?

- A request metric will always be emitted rather than potentially dropped if
it exceeded 1 minute.
If the request exceeds 1 minute, a metric isn't currently emitted?

- Move flag parsing into main to allow current Go versions to work
What is considered "current"? 1.4 and 1.5? How is this validated from an operators perspective (create release / deploy)?

**Comment by fraenkel** [comment]
Dropsonde used to send an HttpStart and HttpStop event. Metron would cache the HttpStart and match the HttpStop if the HttpStart was still available and send an HttpStartStop. The new Dropsonde code just has a single event emitted, HttpStartStop.
The HttpStart was only kept for 1 minute in Metron and no HttpStartStop was sent if there was no match on the HttpStop.

See any travis build on Go tip which has the same issue with Go 1.5.x. Ginkgo/go test fails.
see https://travis-ci.org/cloudfoundry/gorouter/jobs/92984949
func init() is meant for packages to initialize themselves prior to main() running. It is poor practice to have one in main since you are in control.

**Comment by shalako** [comment]
Is this correct?
Given an HTTP request that takes longer than a minute
When the request closes I should see an HttpStartStop message in the firehose
(Currently I will see no message in the firehose)

The change to main() looks like an implementation detail; I'll leave that to the team to review.

**Comment by fraenkel** [comment]
Correct, you will always see an event for every request that completes rather than those that only take < 1 minute.

**Comment by shalako** [comment]
Thank you. Pulling the story in for review.

**Comment by crhino** [comment]
@fraenkel Does the updated dropsonde require go1.5.1? If so we will need to update the golang version in cf-release as well.

**Comment by fraenkel** [comment]
No, just what I am using locally.

**Pull request merged**
